music/urls.py
from django.conf.urls import url
from . import views

app_name="music"

urlpatterns=[

url(r'^$',  views.index, name='index'),
 #/music/album_id
url(r'^(?P<album_id>[0-9]+)/$' , views.details, name='details'),
#/music/album_id/favorite
url(r'^(?P<album_id>[0-9]+)/favorite/$' , views.favorite, name='favorite'),
]

myprojecty/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from __future__ import unicode_literals

from django.db import models


class Album(models.Model):
     artist = models.CharField(max_length=250)
     album_title = models.CharField(max_length=100)
     genre= models.CharField(max_length=100)
     album_logo =models.CharField(max_length=1000)

     def __str__(self):
         return (self.album_title + " " +self.artist)

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title= models.CharField(max_length=250)
    favorite= models.BooleanField(default=False)

    def __str__(self):
           return (self.song_title)

music/views.py
from django.shortcuts import render,get_object_or_404
from .models import Album,Song


def index(request):
   albums=Album.objects.all()

   context={
   'albums': albums,
   }

   return(render(request,"music/index.html",context))

def details(request,album_id):
         album=get_object_or_404(Album,pk=album_id)
         return render(request,"music/details.html",{'album': album})

def favorite(request,album_id):
         album=get_object_or_404(Album,pk=album_id)
         try:
             selected_song=album.song_set.get(pk=request.POST["song"])
         except(KeyError,Song.DoesNotExist):
             return   render(request,"music/details.html",{'album': album, 'error_message': "you did not selected a valid song",})
         else:
                  if (selected_song.favorite==True):
                        selected_song.favorite=False
                        selected_song.save()
                  else:
                       selected_song.favorite= True
                       selected_song.save()

         return render(request,"music/details.html",{'album': album})

music/templates/music/details.html
<h1>Album deatils</h1>
<ul>
  <li>{{album.artist}} </li>
  {% if album.album_title%}
      <li>{{album.album_title}}</l1>
  {% else %}
       <p>NO album title</p>
  {%endif%}           
</ul>
<h1>list of Songs</h1>
{% if album.song_set.all %}
     <form action="{% url 'music:favorite' album.id %}" method="post">
         {% csrf_token %}
         {% for song in album.song_set.all %}
             <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{song.id}}">
             <label for="song{{ forloop.counter }}">
               {{ song.song_title }}
               {% if song.favorite  %}
                       <p>favorite</p>
               {% else %}
                       <p>not favorite</P>
               {% endif %}
             </label><br>
         {% endfor %}
     <input type="submit" name="" value="favorite">
     </form>
  {% else %}
        <p>No songs in this album</p>
  {% endif %}

music/templates/music/index.html
<h1>This is the render funciton</h1>
<ul>
     {% for i in albums  %}
     <li> <a href="{% url 'music:details' i.id %}"> {{i.artist}}</a></li>
 <!--<li><a href="/music/{{i.id}}/">{{i.artist}}</a></li>
//-->
     {% endfor %}
</ul>